// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jywcnectanuvjhdmdamy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5d2NuZWN0YW51dmpoZG1kYW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODcwNjgsImV4cCI6MjA3MzI2MzA2OH0.V9E-_T0B7HOFTZCGpOct9Xgo0q__4Wc8av8h_vdaNMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});